name: Thingaroo
favicon: null
layout_spectrum: 0.702412138460204
typography_spectrum: 0.33922084094956517
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7289256658405066
  lightness: 0.5100129041820765
  saturation: 0.6116880711633712
  rhythmicContrast: 0.3539858835283667
purpose: []
